name: Full Stack CI


on:
  push:
    branches:
      - main


jobs:

  build:

    name: Build Application

    runs-on: ubuntu-latest


    steps:


      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"


      - name: Build Backend
        working-directory: GithubActions
        run: mvn clean package -DskipTests


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"


      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build


      - name: Build Backend Docker Image
        run: |
          docker build \
          -t githubactions-backend:latest \
          ./GithubActions


      - name: Build Frontend Docker Image
        run: |
          docker build \
          -t githubactions-frontend:latest \
          ./frontend


      - name: Show Docker Images
        run: docker images